commits.message = "build(deps): bump ${artifactName} from ${currentVersion} to ${nextVersion}"

pullRequests.grouping = [
  { name = "patches", "title" = "build(deps): patch updates", "filter" = [{"version" = "patch"}] }
]

updatePullRequests = "always"
